BraveBurst.create!([
  {name: "Flare Ride", num_hits: 5, element_id: "1", slug: "flare-ride"},
  {name: "Flare Ride Plus", num_hits: 5, element_id: "1", slug: "flare-ride-plus"},
  {name: "Infinity Burst", num_hits: 6, element_id: "1", slug: "infinity-burst"},
  {name: "Infinity Nova", num_hits: 6, element_id: "1", slug: "infinity-nova"},
  {name: "Estreal Blade", num_hits: 4, element_id: "2", slug: "estreal-blade"},
  {name: "Divine Hale", num_hits: 5, element_id: "2", slug: "divine-hale"},
  {name: "Blizzard Pain", num_hits: 7, element_id: "2", slug: "blizzard-pain"},
  {name: "Absolute Zero", num_hits: 8, element_id: "2", slug: "absolute-zero"},
  {name: "Flash Gale", num_hits: 4, element_id: "6", slug: "flash-gale"},
  {name: "Flash Tornado", num_hits: 5, element_id: "6", slug: "flash-tornado"},
  {name: "Mystral Rage", num_hits: 5, element_id: "6", slug: "mystral-rage"},
  {name: "Eternal Zephyr", num_hits: 6, element_id: "6", slug: "eternal-zephyr"},
  {name: "Thunder Explosion", num_hits: 2, element_id: "5", slug: "thunder-explosion"},
  {name: "Thunder Execution", num_hits: 2, element_id: "5", slug: "thunder-execution"},
  {name: "Thunder Retribution", num_hits: 5, element_id: "5", slug: "thunder-retribution"},
  {name: "Heavenly Thunder", num_hits: 7, element_id: "5", slug: "heavenly-thunder"},
  {name: "Divine Sword", num_hits: 2, element_id: "3", slug: "divine-sword"},
  {name: "Cardinal Judgement", num_hits: 3, element_id: "3", slug: "cardinal-judgement"},
  {name: "Thousand Nemesis", num_hits: 4, element_id: "3", slug: "thousand-nemesis"},
  {name: "Messiah Hazzard", num_hits: 5, element_id: "3", slug: "messiah-hazzard"},
  {name: "Guilty Ash", num_hits: 3, element_id: "4", slug: "guilty-ash"},
  {name: "Gravity Eclipse", num_hits: 4, element_id: "4", slug: "gravity-eclipse"},
  {name: "Void Pillar", num_hits: 4, element_id: "4", slug: "void-pillar"},
  {name: "Vermillion Tower", num_hits: 6, element_id: "4", slug: "vermillion-tower"},
  {name: "Fire Claw Attack", num_hits: 2, element_id: "1", slug: "fire-claw-attack"},
  {name: "Fire Spring Attack", num_hits: 5, element_id: "1", slug: "fire-spring-attack"},
  {name: "Hell Twins Attack", num_hits: 7, element_id: "1", slug: "hell-twins-attack"},
  {name: "Raising Needle", num_hits: 4, element_id: "2", slug: "raising-needle"},
  {name: "Raising Ballad", num_hits: 5, element_id: "2", slug: "raising-ballad"},
  {name: "Raising Glory", num_hits: 6, element_id: "2", slug: "raising-glory"},
  {name: "Carnage Sky", num_hits: 3, element_id: "6", slug: "carnage-sky"},
  {name: "Superior Needle", num_hits: 3, element_id: "6", slug: "superior-needle"},
  {name: "Shooting Star", num_hits: 6, element_id: "6", slug: "shooting-star"},
  {name: "Thunder's Command", num_hits: 0, element_id: "5", slug: "thunder-s-command"},
  {name: "Thunder's Rage", num_hits: 0, element_id: "5", slug: "thunder-s-rage"},
  {name: "Thunder's Reign", num_hits: 0, element_id: "5", slug: "thunder-s-reign"},
  {name: "Rude Thrust", num_hits: 2, element_id: "3", slug: "rude-thrust"},
  {name: "Crude Stab", num_hits: 3, element_id: "3", slug: "crude-stab"},
  {name: "Vulgar Jab", num_hits: 4, element_id: "3", slug: "vulgar-jab"},
  {name: "Special Moonbeam", num_hits: 2, element_id: "4", slug: "special-moonbeam"},
  {name: "Special Swordflash", num_hits: 3, element_id: "4", slug: "special-swordflash"},
  {name: "Special Aurora Flash", num_hits: 4, element_id: "4", slug: "special-aurora-flash"},
  {name: "Gnawing Flame", num_hits: nil, element_id: "1", slug: "gnawing-flame"},
  {name: "Flame Munch", num_hits: nil, element_id: "1", slug: "flame-munch"},
  {name: "Gnawing Water", num_hits: nil, element_id: "2", slug: "gnawing-water"},
  {name: "Water Munch", num_hits: nil, element_id: "2", slug: "water-munch"},
  {name: "Gnawing Wood", num_hits: nil, element_id: "6", slug: "gnawing-wood"},
  {name: "Wood Munch", num_hits: nil, element_id: "6", slug: "wood-munch"},
  {name: "Gnawing Shock", num_hits: nil, element_id: "5", slug: "gnawing-shock"},
  {name: "Shock Munch", num_hits: nil, element_id: "5", slug: "shock-munch"},
  {name: "Gnawing Photon", num_hits: nil, element_id: "3", slug: "gnawing-photon"},
  {name: "Photon Munch", num_hits: nil, element_id: "3", slug: "photon-munch"},
  {name: "Gnawing Shadow", num_hits: nil, element_id: "4", slug: "gnawing-shadow"},
  {name: "Shadow Munch", num_hits: nil, element_id: "4", slug: "shadow-munch"},
  {name: "Eruption", num_hits: 3, element_id: "1", slug: "eruption"},
  {name: "Explosion", num_hits: 5, element_id: "1", slug: "explosion"},
  {name: "Curing", num_hits: 0, element_id: "2", slug: "curing"},
  {name: "Cure Light", num_hits: 0, element_id: "2", slug: "cure-light"},
  {name: "Earth's Water", num_hits: 0, element_id: "6", slug: "earth-s-water"},
  {name: "Arcanadia", num_hits: 0, element_id: "6", slug: "arcanadia"},
  {name: "Thunder Dance", num_hits: 0, element_id: "5", slug: "thunder-dance"},
  {name: "Cure Drill", num_hits: 0, element_id: "5", slug: "cure-drill"},
  {name: "Milky Way", num_hits: 0, element_id: "3", slug: "milky-way"},
  {name: "Saint Benediction", num_hits: 0, element_id: "3", slug: "saint-benediction"},
  {name: "Albatross' Glory", num_hits: 4, element_id: "4", slug: "albatross-glory"},
  {name: "Soul Intention", num_hits: 6, element_id: "4", slug: "soul-intention"},
  {name: "Goblin Attack", num_hits: 4, element_id: "1", slug: "goblin-attack"},
  {name: "Red Strike", num_hits: 5, element_id: "1", slug: "red-strike"},
  {name: "Spiral Lance", num_hits: 4, element_id: "2", slug: "spiral-lance"},
  {name: "Dancing Charge", num_hits: 3, element_id: "2", slug: "dancing-charge"},
  {name: "Power Scream", num_hits: 0, element_id: "6", slug: "power-scream"},
  {name: "Power Intension", num_hits: 0, element_id: "6", slug: "power-intension"},
  {name: "Wind Armor", num_hits: 0, element_id: "5", slug: "wind-armor"},
  {name: "Wind Protection", num_hits: 0, element_id: "5", slug: "wind-protection"},
  {name: "Light Sword", num_hits: 2, element_id: "3", slug: "light-sword"},
  {name: "Blessed Sword", num_hits: 3, element_id: "3", slug: "blessed-sword"},
  {name: "Bone Smash", num_hits: 1, element_id: "4", slug: "bone-smash"},
  {name: "Vorpal Shock", num_hits: 3, element_id: "4", slug: "vorpal-shock"},
  {name: "Poison Gale", num_hits: 4, element_id: "1", slug: "poison-gale"},
  {name: "Venom Gale", num_hits: 6, element_id: "1", slug: "venom-gale"},
  {name: "Crazy Slash", num_hits: 2, element_id: "2", slug: "crazy-slash"},
  {name: "Maximum VWater", num_hits: 4, element_id: "2", slug: "maximum-vwater"},
  {name: "Great Beheading", num_hits: 4, element_id: "6", slug: "great-beheading"},
  {name: "Warrior's Execution", num_hits: 5, element_id: "6", slug: "warrior-s-execution"},
  {name: "Lightning Magnum", num_hits: 3, element_id: "5", slug: "lightning-magnum"},
  {name: "Chariot Magnum", num_hits: 9, element_id: "5", slug: "chariot-magnum"},
  {name: "Heat Bite", num_hits: 2, element_id: "1", slug: "heat-bite"},
  {name: "Keeper Fang", num_hits: 3, element_id: "1", slug: "keeper-fang"},
  {name: "Snake Ripsaw", num_hits: 2, element_id: "2", slug: "snake-ripsaw"},
  {name: "Cold Torture", num_hits: 4, element_id: "2", slug: "cold-torture"},
  {name: "Spirit's Song", num_hits: 0, element_id: "6", slug: "spirit-s-song"},
  {name: "Peaceful Hymn", num_hits: 0, element_id: "6", slug: "peaceful-hymn"},
  {name: "All Out Attack", num_hits: 2, element_id: "5", slug: "all-out-attack"},
  {name: "Destructive Attack", num_hits: 3, element_id: "5", slug: "destructive-attack"},
  {name: "Mirage Horn", num_hits: 6, element_id: "3", slug: "mirage-horn"},
  {name: "Tornado Charge", num_hits: 7, element_id: "3", slug: "tornado-charge"},
  {name: "Golgon Eye", num_hits: 4, element_id: "4", slug: "golgon-eye"},
  {name: "Black Snake Heart", num_hits: 4, element_id: "4", slug: "black-snake-heart"},
  {name: "Blaze Force", num_hits: 0, element_id: "1", slug: "blaze-force"},
  {name: "Hell Blaze", num_hits: 0, element_id: "1", slug: "hell-blaze"},
  {name: "Recure Rise", num_hits: 0, element_id: "2", slug: "recure-rise"},
  {name: "Life Breath", num_hits: 0, element_id: "2", slug: "life-breath"},
  {name: "Terra Firma", num_hits: 3, element_id: "6", slug: "terra-firma"},
  {name: "Grand Storm", num_hits: 5, element_id: "6", slug: "grand-storm"},
  {name: "Soul Feathers", num_hits: 0, element_id: "5", slug: "soul-feathers"},
  {name: "Lost Soul Crystal", num_hits: 0, element_id: "5", slug: "lost-soul-crystal"},
  {name: "Holy Prayer", num_hits: 0, element_id: "3", slug: "holy-prayer"},
  {name: "Saint's Gospel", num_hits: 0, element_id: "3", slug: "saint-s-gospel"},
  {name: "Monster Dance", num_hits: 0, element_id: "4", slug: "monster-dance"},
  {name: "Demon Kiss", num_hits: 0, element_id: "4", slug: "demon-kiss"},
  {name: "Fire Breath", num_hits: 3, element_id: "1", slug: "fire-breath"},
  {name: "Mega Breath", num_hits: 5, element_id: "1", slug: "mega-breath"},
  {name: "Prism Shower", num_hits: 0, element_id: "2", slug: "prism-shower"},
  {name: "Miracle Shower", num_hits: 0, element_id: "2", slug: "miracle-shower"},
  {name: "Manalight Circle", num_hits: 0, element_id: "6", slug: "manalight-circle"},
  {name: "Elemental Wall", num_hits: 0, element_id: "6", slug: "elemental-wall"},
  {name: "Thunderstorm", num_hits: 5, element_id: "5", slug: "thunderstorm"},
  {name: "Valza Riser", num_hits: 5, element_id: "5", slug: "valza-riser"},
  {name: "Sar Air Raid", num_hits: 4, element_id: "3", slug: "sar-air-raid"},
  {name: "Valkyrie Tempest", num_hits: 7, element_id: "3", slug: "valkyrie-tempest"},
  {name: "Blood Gluttony", num_hits: 3, element_id: "4", slug: "blood-gluttony"},
  {name: "Abyss Gale", num_hits: 5, element_id: "4", slug: "abyss-gale"},
  {name: "Dragon's Expulsion", num_hits: 8, element_id: "1", slug: "dragon-s-expulsion"},
  {name: "Dragon's Execution", num_hits: 9, element_id: "1", slug: "dragon-s-execution"},
  {name: "Frigid Combo", num_hits: 5, element_id: "2", slug: "frigid-combo"},
  {name: "Royal Water Blade", num_hits: 7, element_id: "2", slug: "royal-water-blade"},
  {name: "Royal SlWater", num_hits: 6, element_id: "6", slug: "royal-slwater"},
  {name: "Royal Slash", num_hits: 8, element_id: "6", slug: "royal-slash"},
  {name: "Flash Stream", num_hits: 5, element_id: "5", slug: "flash-stream"},
  {name: "Dual Arch", num_hits: 7, element_id: "5", slug: "dual-arch"},
  {name: "Holy Ray", num_hits: 5, element_id: "3", slug: "holy-ray"},
  {name: "Star Children", num_hits: 10, element_id: "3", slug: "star-children"},
  {name: "Catastrophe", num_hits: 6, element_id: "4", slug: "catastrophe"},
  {name: "Dark Matter", num_hits: 8, element_id: "4", slug: "dark-matter"},
  {name: "Burning Feather", num_hits: 0, element_id: "1", slug: "burning-feather"},
  {name: "Ignited Feather", num_hits: 0, element_id: "1", slug: "ignited-feather"},
  {name: "Phoenix Feather", num_hits: 0, element_id: "1", slug: "phoenix-feather"},
  {name: "Tidal Wave", num_hits: 4, element_id: "2", slug: "tidal-wave"},
  {name: "Maelstrom", num_hits: 5, element_id: "2", slug: "maelstrom"},
  {name: "Calamity Wave", num_hits: 6, element_id: "2", slug: "calamity-wave"},
  {name: "Lucent Purge", num_hits: 0, element_id: "6", slug: "lucent-purge"},
  {name: "Benevolence Purge", num_hits: 0, element_id: "6", slug: "benevolence-purge"},
  {name: "God Purge", num_hits: 0, element_id: "6", slug: "god-purge"},
  {name: "Crash Bind", num_hits: 2, element_id: "5", slug: "crash-bind"},
  {name: "Meteor Zapper", num_hits: 3, element_id: "5", slug: "meteor-zapper"},
  {name: "Rodmagia Grudge", num_hits: 4, element_id: "5", slug: "rodmagia-grudge"},
  {name: "Dragon VoWater", num_hits: 4, element_id: "3", slug: "dragon-vowater"},
  {name: "Genocide Blaster", num_hits: 5, element_id: "3", slug: "genocide-blaster"},
  {name: "Skydragon Gun", num_hits: 6, element_id: "3", slug: "skydragon-gun"},
  {name: "Climb Pain", num_hits: 4, element_id: "4", slug: "climb-pain"},
  {name: "Chaos Fall", num_hits: 5, element_id: "4", slug: "chaos-fall"},
  {name: "World of Darkness", num_hits: 6, element_id: "4", slug: "world-of-darkness"},
  {name: "Blazing Inferno", num_hits: 4, element_id: "1", slug: "blazing-inferno"},
  {name: "Prometheus Burn", num_hits: 5, element_id: "1", slug: "prometheus-burn"},
  {name: "Anguish Blade", num_hits: 10, element_id: "1", slug: "anguish-blade"},
  {name: "Ocean Whirlpool", num_hits: 4, element_id: "2", slug: "ocean-whirlpool"},
  {name: "Tempest Gallows", num_hits: 5, element_id: "2", slug: "tempest-gallows"},
  {name: "Cyclone Disaster", num_hits: 6, element_id: "2", slug: "cyclone-disaster"},
  {name: "Zafonic Bullet", num_hits: 10, element_id: "6", slug: "zafonic-bullet"},
  {name: "Genocidal Grit", num_hits: 15, element_id: "6", slug: "genocidal-grit"},
  {name: "Shining Zork", num_hits: 20, element_id: "6", slug: "shining-zork"},
  {name: "Cross Layer Blitz", num_hits: 5, element_id: "5", slug: "cross-layer-blitz"},
  {name: "Elznet Saber", num_hits: 5, element_id: "5", slug: "elznet-saber"},
  {name: "Genocide Levin", num_hits: 7, element_id: "5", slug: "genocide-levin"},
  {name: "Galactic Volley", num_hits: 2, element_id: "3", slug: "galactic-volley"},
  {name: "Sacred Force", num_hits: 4, element_id: "3", slug: "sacred-force"},
  {name: "Astral Nova", num_hits: 6, element_id: "3", slug: "astral-nova"},
  {name: "Shadow Insult", num_hits: 3, element_id: "4", slug: "shadow-insult"},
  {name: "Crimson Reaper", num_hits: 7, element_id: "4", slug: "crimson-reaper"},
  {name: "Abaddon Eater", num_hits: 8, element_id: "4", slug: "abaddon-eater"},
  {name: nil, num_hits: nil, element_id: "1", slug: nil},
  {name: "Focal Blast", num_hits: 4, element_id: "1", slug: "focal-blast"},
  {name: "Grenade buster", num_hits: 5, element_id: "1", slug: "grenade-buster"},
  {name: "Ignis Nebula", num_hits: 6, element_id: "1", slug: "ignis-nebula"},
  {name: "Glacier Circle", num_hits: 5, element_id: "2", slug: "glacier-circle"},
  {name: "Avalanche", num_hits: 8, element_id: "2", slug: "avalanche"},
  {name: "Eternal Winter", num_hits: 10, element_id: "2", slug: "eternal-winter"},
  {name: "Tierra Knuckle", num_hits: 3, element_id: "6", slug: "tierra-knuckle"},
  {name: "Adamant Crack", num_hits: 4, element_id: "6", slug: "adamant-crack"},
  {name: "Grand Geyser", num_hits: 5, element_id: "6", slug: "grand-geyser"},
  {name: "Quick Kick", num_hits: 3, element_id: "5", slug: "quick-kick"},
  {name: "Spark Kick", num_hits: 4, element_id: "5", slug: "spark-kick"},
  {name: "Brave Edge", num_hits: 4, element_id: "3", slug: "brave-edge"},
  {name: "Brave Impact", num_hits: 5, element_id: "3", slug: "brave-impact"},
  {name: "Star Dust Fall", num_hits: 7, element_id: "3", slug: "star-dust-fall"},
  {name: "Ninjitsu: Blade Drop", num_hits: 4, element_id: "4", slug: "ninjitsu-blade-drop"},
  {name: "Assassin Dagger", num_hits: 5, element_id: "4", slug: "assassin-dagger"},
  {name: "Ritual: Foreign Demon", num_hits: 6, element_id: "4", slug: "ritual-foreign-demon"},
  {name: "Lovely Cooking", num_hits: 0, element_id: "1", slug: "lovely-cooking"},
  {name: "Hearty Dish", num_hits: 0, element_id: "1", slug: "hearty-dish"},
  {name: "Gourmet Dish", num_hits: 0, element_id: "1", slug: "gourmet-dish"},
  {name: "Aether Guard", num_hits: 0, element_id: "2", slug: "aether-guard"},
  {name: "Aether Shield", num_hits: 0, element_id: "2", slug: "aether-shield"},
  {name: "GuardianForce", num_hits: 0, element_id: "2", slug: "guardianforce"},
  {name: "Mirage Needle", num_hits: 6, element_id: "6", slug: "mirage-needle"},
  {name: "Million Thrust", num_hits: 7, element_id: "6", slug: "million-thrust"},
  {name: "Heavy Riposte", num_hits: 10, element_id: "6", slug: "heavy-riposte"},
  {name: "Spark Hammer", num_hits: 2, element_id: "5", slug: "spark-hammer"},
  {name: "Thunder Crush", num_hits: 3, element_id: "5", slug: "thunder-crush"},
  {name: "Lightning Smash", num_hits: 4, element_id: "5", slug: "lightning-smash"},
  {name: "Dragon Slayer", num_hits: 7, element_id: "3", slug: "dragon-slayer"},
  {name: "God Slayer", num_hits: 7, element_id: "3", slug: "god-slayer"},
  {name: "Radiant Heaven", num_hits: 8, element_id: "3", slug: "radiant-heaven"},
  {name: "Gravity Bomb", num_hits: 5, element_id: "4", slug: "gravity-bomb"},
  {name: "Glasya Labolas", num_hits: 6, element_id: "4", slug: "glasya-labolas"},
  {name: "Black Hole", num_hits: 8, element_id: "4", slug: "black-hole"},
  {name: "Burning Spirit", num_hits: 3, element_id: "1", slug: "burning-spirit"},
  {name: "Flaming Spirit", num_hits: 4, element_id: "1", slug: "flaming-spirit"},
  {name: "Balzing Spirit", num_hits: 5, element_id: "1", slug: "balzing-spirit"},
  {name: "Solid Ice", num_hits: 5, element_id: "2", slug: "solid-ice"},
  {name: "Diamond Dust", num_hits: 5, element_id: "2", slug: "diamond-dust"},
  {name: "Grand Bash", num_hits: 4, element_id: "6", slug: "grand-bash"},
  {name: "Astro Bash", num_hits: 6, element_id: "6", slug: "astro-bash"},
  {name: "Grand Cross", num_hits: 8, element_id: "6", slug: "grand-cross"},
  {name: "Lightning Arrow", num_hits: 5, element_id: "5", slug: "lightning-arrow"},
  {name: "Pulsar Fall", num_hits: 6, element_id: "5", slug: "pulsar-fall"},
  {name: "Rising Nova", num_hits: 7, element_id: "5", slug: "rising-nova"},
  {name: "Healing Samba", num_hits: nil, element_id: "5", slug: "healing-samba"},
  {name: "Dragon Voice", num_hits: 5, element_id: "1", slug: "dragon-voice"},
  {name: "Dragon Scream", num_hits: 7, element_id: "1", slug: "dragon-scream"},
  {name: "Dragon Rage", num_hits: 10, element_id: "1", slug: "dragon-rage"},
  {name: "Crystal Bullet", num_hits: 6, element_id: "2", slug: "crystal-bullet"},
  {name: "Diamon Rebel", num_hits: nil, element_id: "2", slug: "diamon-rebel"},
  {name: "Ancient Bullet", num_hits: 14, element_id: "2", slug: "ancient-bullet"},
  {name: "Star Twins", num_hits: 4, element_id: "6", slug: "star-twins"},
  {name: "Twins Radiation", num_hits: 6, element_id: "6", slug: "twins-radiation"},
  {name: "Southern Cross", num_hits: 8, element_id: "6", slug: "southern-cross"},
  {name: "Thunder Spear Attack", num_hits: nil, element_id: "5", slug: "thunder-spear-attack"},
  {name: "Thunder Spear Combo", num_hits: nil, element_id: "5", slug: "thunder-spear-combo"},
  {name: "Thunder Spear Barrage", num_hits: 7, element_id: "5", slug: "thunder-spear-barrage"},
  {name: "Halcion Hack", num_hits: 8, element_id: "3", slug: "halcion-hack"},
  {name: "Destructive Chain", num_hits: 9, element_id: "3", slug: "destructive-chain"},
  {name: "Sword Storm Barrage", num_hits: 10, element_id: "3", slug: "sword-storm-barrage"},
  {name: "Firefly", num_hits: 6, element_id: "4", slug: "firefly"},
  {name: "Ethernal Firefly", num_hits: 8, element_id: "4", slug: "ethernal-firefly"},
  {name: "Celestial Firefly", num_hits: 10, element_id: "4", slug: "celestial-firefly"},
  {name: "Poisonado", num_hits: nil, element_id: "1", slug: "poisonado"}
])
Element.create!([
  {name: "fire"},
  {name: "water"},
  {name: "light"},
  {name: "dark"},
  {name: "thunder"},
  {name: "earth"},
  {name: "multi"}
])
Unit.create!([
  {name: "Fencer Vargas", description: "A swordsman from the ruined Agni Empire, he later became one of the Six Heroes. Proud of his late father, a Knight in the Order of Agni, he trained in the long sword, becoming a formidable knight. Although he is well-known for his countless victories over other warriors, he still considers himself inexperienced and continues to train with great zeal.", no: 1, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 1, numhits: 3, slug: "fencer-vargas", realname: nil, cost: nil, max_lvl: nil},
  {name: "Burning Vargas", description: nil, no: 2, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 2, numhits: 3, slug: "burning-vargas", realname: nil, cost: 4, max_lvl: 40},
  {name: "Fire King Vargas", description: nil, no: 3, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 3, numhits: 4, slug: "fire-king-vargas", realname: nil, cost: 8, max_lvl: 60},
  {name: "Fire God Vargas", description: nil, no: 4, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 4, numhits: 6, slug: "fire-god-vargas", realname: nil, cost: 10, max_lvl: 80},
  {name: "Selena", description: nil, no: 5, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 5, numhits: 2, slug: "selena", realname: nil, cost: 2, max_lvl: 12},
  {name: "Ice Selena", description: nil, no: 6, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 6, numhits: 2, slug: "ice-selena", realname: nil, cost: 4, max_lvl: 40},
  {name: "Iron Magress", description: nil, no: 21, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 21, numhits: 1, slug: "iron-magress", realname: nil, cost: 2, max_lvl: 12},
  {name: "Heavy Magress", description: nil, no: 22, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 22, numhits: 1, slug: "heavy-magress", realname: nil, cost: 4, max_lvl: 40},
  {name: "Ice Queen Selena", description: nil, no: 7, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 7, numhits: 4, slug: "ice-queen-selena", realname: nil, cost: 8, max_lvl: 60},
  {name: "Ice God Selena", description: nil, no: 8, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 8, numhits: 4, slug: "ice-god-selena", realname: nil, cost: 10, max_lvl: 80},
  {name: "Pikeman Lance", description: nil, no: 9, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 9, numhits: 3, slug: "pikeman-lance", realname: nil, cost: 2, max_lvl: 12},
  {name: "Vine Pike Lance", description: nil, no: 10, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 10, numhits: 4, slug: "vine-pike-lance", realname: nil, cost: 4, max_lvl: 40},
  {name: "Earth Pike Lance", description: nil, no: 11, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 11, numhits: 4, slug: "earth-pike-lance", realname: nil, cost: 8, max_lvl: 60},
  {name: "Nature God Lance", description: nil, no: 12, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 12, numhits: 4, slug: "nature-god-lance", realname: nil, cost: 10, max_lvl: 80},
  {name: "Warrior Eze", description: nil, no: 13, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 13, numhits: 1, slug: "warrior-eze", realname: nil, cost: 2, max_lvl: 12},
  {name: "Thunder Eze", description: nil, no: 14, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 14, numhits: 1, slug: "thunder-eze", realname: nil, cost: 4, max_lvl: 40},
  {name: "Thunder King Eze", description: nil, no: 15, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 15, numhits: 2, slug: "thunder-king-eze", realname: nil, cost: 8, max_lvl: 60},
  {name: "Thunder God Eze", description: nil, no: 16, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 16, numhits: 5, slug: "thunder-god-eze", realname: nil, cost: 10, max_lvl: 80},
  {name: "Squire Atro", description: nil, no: 17, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 17, numhits: 1, slug: "squire-atro", realname: nil, cost: 2, max_lvl: 12},
  {name: "Knight Atro", description: nil, no: 18, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 18, numhits: 1, slug: "knight-atro", realname: nil, cost: 4, max_lvl: 40},
  {name: "Holy Knight Atro", description: nil, no: 19, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 19, numhits: 2, slug: "holy-knight-atro", realname: nil, cost: 8, max_lvl: 60},
  {name: "God Atro", description: nil, no: 20, element_id: 3, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 20, numhits: 3, slug: "god-atro", realname: nil, cost: 10, max_lvl: 80},
  {name: "Black Magress", description: nil, no: 23, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 23, numhits: 2, slug: "black-magress", realname: nil, cost: 8, max_lvl: 60},
  {name: "Death Magress", description: nil, no: 24, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 24, numhits: 3, slug: "death-magress", realname: nil, cost: 10, max_lvl: 80},
  {name: "Beast Zegar", description: nil, no: 25, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 25, numhits: 2, slug: "beast-zegar", realname: nil, cost: 3, max_lvl: 30},
  {name: "Rage Beast Zegar", description: nil, no: 26, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 26, numhits: 4, slug: "rage-beast-zegar", realname: nil, cost: 5, max_lvl: 40},
  {name: "Fire Beast Zegar", description: nil, no: 27, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 27, numhits: 7, slug: "fire-beast-zegar", realname: nil, cost: 9, max_lvl: 60},
  {name: "Zephu", description: nil, no: 28, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 28, numhits: 3, slug: "zephu", realname: nil, cost: 3, max_lvl: 30},
  {name: "Knight Zephu", description: nil, no: 29, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 29, numhits: 4, slug: "knight-zephu", realname: nil, cost: 5, max_lvl: 40},
  {name: "Dragoon Zephu", description: nil, no: 30, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 30, numhits: 5, slug: "dragoon-zephu", realname: nil, cost: 9, max_lvl: 60},
  {name: "Archer Lario", description: nil, no: 31, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 31, numhits: 3, slug: "archer-lario", realname: nil, cost: 3, max_lvl: 30},
  {name: "Marksman Lario", description: nil, no: 32, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 32, numhits: 3, slug: "marksman-lario", realname: nil, cost: 5, max_lvl: 40},
  {name: "Hawkeye Lario", description: nil, no: 33, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 33, numhits: 6, slug: "hawkeye-lario", realname: nil, cost: 9, max_lvl: 60},
  {name: "Advisor Weiss", description: nil, no: 34, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 34, numhits: 3, slug: "advisor-weiss", realname: nil, cost: 3, max_lvl: 30},
  {name: "Strategist Weiss", description: nil, no: 35, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 35, numhits: 5, slug: "strategist-weiss", realname: nil, cost: 5, max_lvl: 40},
  {name: "Luna", description: nil, no: 37, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 37, numhits: 2, slug: "luna", realname: nil, cost: 3, max_lvl: 30},
  {name: "Sunshine Luna", description: nil, no: 38, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 38, numhits: 3, slug: "sunshine-luna", realname: nil, cost: 5, max_lvl: 40},
  {name: "Holy Queen Luna", description: nil, no: 39, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 39, numhits: 4, slug: "holy-queen-luna", realname: nil, cost: 9, max_lvl: 60},
  {name: "Mifune", description: nil, no: 40, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 40, numhits: 2, slug: "mifune", realname: nil, cost: 3, max_lvl: 30},
  {name: "Samurai Mifune", description: nil, no: 41, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 41, numhits: 3, slug: "samurai-mifune", realname: nil, cost: 5, max_lvl: 40},
  {name: "God Blade Mifune", description: nil, no: 42, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 42, numhits: 4, slug: "god-blade-mifune", realname: nil, cost: 9, max_lvl: 60},
  {name: "Burny", description: nil, no: 43, element_id: 1, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 43, numhits: nil, slug: "burny", realname: nil, cost: 1, max_lvl: 10},
  {name: "King Burny", description: nil, no: 44, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 44, numhits: nil, slug: "king-burny", realname: nil, cost: 3, max_lvl: 30},
  {name: "Squirty", description: nil, no: 45, element_id: 2, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 45, numhits: nil, slug: "squirty", realname: nil, cost: 1, max_lvl: 10},
  {name: "Mossy", description: nil, no: 47, element_id: 6, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 47, numhits: nil, slug: "mossy", realname: nil, cost: 1, max_lvl: 10},
  {name: "King Mossy", description: nil, no: 48, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 48, numhits: nil, slug: "king-mossy", realname: nil, cost: 3, max_lvl: 30},
  {name: "Sparky", description: nil, no: 49, element_id: 5, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 49, numhits: nil, slug: "sparky", realname: nil, cost: 1, max_lvl: 10},
  {name: "King Sparky", description: nil, no: 50, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 50, numhits: nil, slug: "king-sparky", realname: nil, cost: 3, max_lvl: 30},
  {name: "Glowy", description: nil, no: 51, element_id: 3, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 51, numhits: nil, slug: "glowy", realname: nil, cost: 1, max_lvl: 10},
  {name: "King Glowy", description: nil, no: 52, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 52, numhits: nil, slug: "king-glowy", realname: nil, cost: 3, max_lvl: 30},
  {name: "Gloomy", description: nil, no: 53, element_id: 4, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 53, numhits: nil, slug: "gloomy", realname: nil, cost: 1, max_lvl: 10},
  {name: "King Gloomy", description: nil, no: 54, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 54, numhits: nil, slug: "king-gloomy", realname: nil, cost: 3, max_lvl: 30},
  {name: "Witch Liza", description: nil, no: 55, element_id: 1, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 55, numhits: 3, slug: "witch-liza", realname: nil, cost: 2, max_lvl: 15},
  {name: "Warlock Liza", description: nil, no: 56, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 56, numhits: 5, slug: "warlock-liza", realname: nil, cost: 4, max_lvl: 30},
  {name: "Priest Merith", description: nil, no: 57, element_id: 2, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 57, numhits: 3, slug: "priest-merith", realname: nil, cost: 2, max_lvl: 15},
  {name: "Healer Merith", description: nil, no: 58, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 58, numhits: 5, slug: "healer-merith", realname: nil, cost: 4, max_lvl: 30},
  {name: "Time Mage Claris", description: nil, no: 60, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 60, numhits: 5, slug: "time-mage-claris", realname: nil, cost: 4, max_lvl: 30},
  {name: "Dancer May", description: nil, no: 61, element_id: 5, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 61, numhits: 3, slug: "dancer-may", realname: nil, cost: 2, max_lvl: 15},
  {name: "High Dancer May", description: nil, no: 62, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 62, numhits: 5, slug: "high-dancer-may", realname: nil, cost: 4, max_lvl: 30},
  {name: "Sage Mimir", description: nil, no: 63, element_id: 3, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 63, numhits: 3, slug: "sage-mimir", realname: nil, cost: 2, max_lvl: 15},
  {name: "Light LordMimir", description: nil, no: 64, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 64, numhits: 5, slug: "light-lordmimir", realname: nil, cost: 4, max_lvl: 30},
  {name: "Sorceress Lily", description: nil, no: 65, element_id: 4, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 65, numhits: 3, slug: "sorceress-lily", realname: nil, cost: 2, max_lvl: 15},
  {name: "Magician Lily", description: nil, no: 66, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 66, numhits: 5, slug: "magician-lily", realname: nil, cost: 4, max_lvl: 30},
  {name: "Goblin", description: nil, no: 67, element_id: 1, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 67, numhits: 1, slug: "goblin", realname: nil, cost: 2, max_lvl: 12},
  {name: "Redcap", description: nil, no: 68, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 68, numhits: 1, slug: "redcap", realname: nil, cost: 4, max_lvl: 30},
  {name: "Merman", description: nil, no: 69, element_id: 2, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 69, numhits: 2, slug: "merman", realname: nil, cost: 2, max_lvl: 12},
  {name: "Sahuagin", description: nil, no: 70, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 70, numhits: 4, slug: "sahuagin", realname: nil, cost: 4, max_lvl: 30},
  {name: "Mandragora", description: nil, no: 71, element_id: 6, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 71, numhits: 3, slug: "mandragora", realname: nil, cost: 2, max_lvl: 12},
  {name: "Polevik", description: nil, no: 72, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 72, numhits: 4, slug: "polevik", realname: nil, cost: 4, max_lvl: 30},
  {name: "Harpy", description: nil, no: 73, element_id: 5, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 73, numhits: 3, slug: "harpy", realname: nil, cost: 2, max_lvl: 12},
  {name: "Aero", description: nil, no: 74, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 74, numhits: 6, slug: "aero", realname: nil, cost: 4, max_lvl: 30},
  {name: "Angel", description: nil, no: 75, element_id: 3, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 75, numhits: 1, slug: "angel", realname: nil, cost: 2, max_lvl: 12},
  {name: "Archangel", description: nil, no: 76, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 76, numhits: 2, slug: "archangel", realname: nil, cost: 4, max_lvl: 30},
  {name: "Skeleton", description: nil, no: 77, element_id: 4, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 77, numhits: 2, slug: "skeleton", realname: nil, cost: 2, max_lvl: 12},
  {name: "Skeleton King", description: nil, no: 78, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 78, numhits: 2, slug: "skeleton-king", realname: nil, cost: 4, max_lvl: 30},
  {name: "Head Thief Leon", description: nil, no: 80, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 80, numhits: 6, slug: "head-thief-leon", realname: nil, cost: 6, max_lvl: 40},
  {name: "Pirate Verica", description: nil, no: 81, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 81, numhits: 2, slug: "pirate-verica", realname: nil, cost: 3, max_lvl: 30},
  {name: "Plunderer Verica", description: nil, no: 82, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 82, numhits: 4, slug: "plunderer-verica", realname: nil, cost: 6, max_lvl: 40},
  {name: "Bandit Zaza", description: nil, no: 83, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 83, numhits: 4, slug: "bandit-zaza", realname: nil, cost: 3, max_lvl: 30},
  {name: "Head Bandit Zaza", description: nil, no: 84, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 84, numhits: 5, slug: "head-bandit-zaza", realname: nil, cost: 6, max_lvl: 40},
  {name: "Sky Pirate Grafl", description: nil, no: 85, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 85, numhits: 3, slug: "sky-pirate-grafl", realname: nil, cost: 3, max_lvl: 30},
  {name: "Sky Boss Grafl", description: nil, no: 86, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 86, numhits: 6, slug: "sky-boss-grafl", realname: nil, cost: 6, max_lvl: 40},
  {name: "Orthos", description: nil, no: 87, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 87, numhits: 2, slug: "orthos", realname: nil, cost: 2, max_lvl: 30},
  {name: "Cerberus", description: nil, no: 88, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 88, numhits: 5, slug: "cerberus", realname: nil, cost: 5, max_lvl: 40},
  {name: "Ramia", description: nil, no: 89, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 89, numhits: 2, slug: "ramia", realname: nil, cost: 2, max_lvl: 30},
  {name: "Scylla", description: nil, no: 90, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 90, numhits: 4, slug: "scylla", realname: nil, cost: 5, max_lvl: 40},
  {name: "Fairy", description: nil, no: 91, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 91, numhits: 3, slug: "fairy", realname: nil, cost: 2, max_lvl: 30},
  {name: "Titania", description: nil, no: 92, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 92, numhits: 4, slug: "titania", realname: nil, cost: 5, max_lvl: 40},
  {name: "Minotaur", description: nil, no: 93, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 93, numhits: 1, slug: "minotaur", realname: nil, cost: 2, max_lvl: 30},
  {name: "Cyclops", description: nil, no: 94, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 94, numhits: 5, slug: "cyclops", realname: nil, cost: 5, max_lvl: 40},
  {name: "Unicorn", description: nil, no: 95, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 95, numhits: 5, slug: "unicorn", realname: nil, cost: 3, max_lvl: 30},
  {name: "Pegasus", description: nil, no: 96, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 96, numhits: 5, slug: "pegasus", realname: nil, cost: 6, max_lvl: 40},
  {name: "Medusa", description: nil, no: 97, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 97, numhits: 3, slug: "medusa", realname: nil, cost: 3, max_lvl: 30},
  {name: "Salamander", description: nil, no: 99, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 99, numhits: 3, slug: "salamander", realname: nil, cost: 2, max_lvl: 30},
  {name: "Ifrit", description: nil, no: 100, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 100, numhits: 6, slug: "ifrit", realname: nil, cost: 4, max_lvl: 40},
  {name: "Rantoul", description: nil, no: 101, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 101, numhits: 3, slug: "rantoul", realname: nil, cost: 2, max_lvl: 30},
  {name: "Legtos", description: nil, no: 102, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 102, numhits: 5, slug: "legtos", realname: nil, cost: 4, max_lvl: 40},
  {name: "Trent", description: nil, no: 103, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 103, numhits: 3, slug: "trent", realname: nil, cost: 2, max_lvl: 30},
  {name: "Ent", description: nil, no: 104, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 104, numhits: 5, slug: "ent", realname: nil, cost: 4, max_lvl: 40},
  {name: "Sylph", description: nil, no: 105, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 105, numhits: 3, slug: "sylph", realname: nil, cost: 2, max_lvl: 30},
  {name: "Djin", description: nil, no: 106, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 106, numhits: 5, slug: "djin", realname: nil, cost: 4, max_lvl: 40},
  {name: "Priestess Maria", description: nil, no: 107, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 107, numhits: 3, slug: "priestess-maria", realname: nil, cost: 2, max_lvl: 30},
  {name: "Angel Maria", description: nil, no: 108, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 108, numhits: 5, slug: "angel-maria", realname: nil, cost: 4, max_lvl: 40},
  {name: "Lilin", description: nil, no: 109, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 109, numhits: 6, slug: "lilin", realname: nil, cost: 2, max_lvl: 30},
  {name: "Succubus", description: nil, no: 110, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 110, numhits: 6, slug: "succubus", realname: nil, cost: 4, max_lvl: 40},
  {name: "Dragon Graven", description: nil, no: 112, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 112, numhits: 5, slug: "dragon-graven", realname: nil, cost: 8, max_lvl: 60},
  {name: "Undine", description: nil, no: 113, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 113, numhits: 3, slug: "undine", realname: nil, cost: 5, max_lvl: 40},
  {name: "Siren", description: nil, no: 114, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 114, numhits: 5, slug: "siren", realname: nil, cost: 8, max_lvl: 60},
  {name: "Dryad", description: nil, no: 115, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 115, numhits: 3, slug: "dryad", realname: nil, cost: 5, max_lvl: 40},
  {name: "High Elf", description: nil, no: 116, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 116, numhits: 5, slug: "high-elf", realname: nil, cost: 8, max_lvl: 60},
  {name: "Thunderbird", description: nil, no: 117, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 117, numhits: 3, slug: "thunderbird", realname: nil, cost: 5, max_lvl: 40},
  {name: "Great Falcon Ziz", description: nil, no: 118, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 118, numhits: 4, slug: "great-falcon-ziz", realname: nil, cost: 8, max_lvl: 60},
  {name: "Valkyrie", description: nil, no: 119, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 119, numhits: 5, slug: "valkyrie", realname: nil, cost: 5, max_lvl: 40},
  {name: "Sky Hero Athena", description: nil, no: 120, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 120, numhits: 6, slug: "sky-hero-athena", realname: nil, cost: 8, max_lvl: 60},
  {name: "Vampire", description: nil, no: 121, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 121, numhits: 3, slug: "vampire", realname: nil, cost: 5, max_lvl: 40},
  {name: "Lich", description: nil, no: 122, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 122, numhits: 5, slug: "lich", realname: nil, cost: 8, max_lvl: 60},
  {name: "Knight Agni", description: nil, no: 123, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 123, numhits: 8, slug: "knight-agni", realname: nil, cost: 5, max_lvl: 40},
  {name: "Fire Knight Agni", description: nil, no: 124, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 124, numhits: 9, slug: "fire-knight-agni", realname: nil, cost: 8, max_lvl: 60},
  {name: "Knight Sergio", description: nil, no: 125, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 125, numhits: 2, slug: "knight-sergio", realname: nil, cost: 5, max_lvl: 40},
  {name: "Princess Lidlith", description: nil, no: 127, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 127, numhits: 6, slug: "princess-lidlith", realname: nil, cost: 5, max_lvl: 40},
  {name: "Queen Lidlith", description: nil, no: 128, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 128, numhits: 8, slug: "queen-lidlith", realname: nil, cost: 8, max_lvl: 60},
  {name: "Sky Knight Falma", description: nil, no: 129, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 129, numhits: 5, slug: "sky-knight-falma", realname: nil, cost: 5, max_lvl: 40},
  {name: "Sky King Falma", description: nil, no: 130, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 130, numhits: 7, slug: "sky-king-falma", realname: nil, cost: 8, max_lvl: 60},
  {name: "Cowboy Heidt", description: nil, no: 131, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 131, numhits: 5, slug: "cowboy-heidt", realname: nil, cost: 5, max_lvl: 40},
  {name: "Holy Shot Heidt", description: nil, no: 132, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 132, numhits: 10, slug: "holy-shot-heidt", realname: nil, cost: 8, max_lvl: 60},
  {name: "Shida", description: nil, no: 133, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 133, numhits: 6, slug: "shida", realname: nil, cost: 5, max_lvl: 40},
  {name: "Garroter Shida", description: nil, no: 134, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 134, numhits: 8, slug: "garroter-shida", realname: nil, cost: 8, max_lvl: 60},
  {name: "Phoenix", description: nil, no: 135, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 135, numhits: 3, slug: "phoenix", realname: nil, cost: 5, max_lvl: 40},
  {name: "Lava Phoenix", description: nil, no: 136, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 136, numhits: 4, slug: "lava-phoenix", realname: nil, cost: 8, max_lvl: 60},
  {name: "God Phoenix", description: nil, no: 137, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 137, numhits: 6, slug: "god-phoenix", realname: nil, cost: 12, max_lvl: 80},
  {name: "Leviathan", description: nil, no: 138, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 138, numhits: 3, slug: "leviathan", realname: nil, cost: 5, max_lvl: 40},
  {name: "Loch Ness", description: nil, no: 139, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 139, numhits: 4, slug: "loch-ness", realname: nil, cost: 8, max_lvl: 60},
  {name: "Malnaplus", description: nil, no: 140, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 140, numhits: 5, slug: "malnaplus", realname: nil, cost: 12, max_lvl: 80},
  {name: "Great Tree Alneu", description: nil, no: 141, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 141, numhits: 3, slug: "great-tree-alneu", realname: nil, cost: 5, max_lvl: 40},
  {name: "God Tree Eltri", description: nil, no: 143, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 143, numhits: 6, slug: "god-tree-eltri", realname: nil, cost: 12, max_lvl: 80},
  {name: "Behemoth", description: nil, no: 144, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 144, numhits: 1, slug: "behemoth", realname: nil, cost: 5, max_lvl: 40},
  {name: "King Behemoth", description: nil, no: 145, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 145, numhits: 3, slug: "king-behemoth", realname: nil, cost: 8, max_lvl: 60},
  {name: "Alpha Behemoth", description: nil, no: 146, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 146, numhits: 3, slug: "alpha-behemoth", realname: nil, cost: 12, max_lvl: 80},
  {name: "Wyvern", description: nil, no: 147, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 147, numhits: 3, slug: "wyvern", realname: nil, cost: 5, max_lvl: 40},
  {name: "Bahamut", description: nil, no: 148, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 148, numhits: 4, slug: "bahamut", realname: nil, cost: 8, max_lvl: 60},
  {name: "Rameldria", description: nil, no: 149, element_id: 3, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 149, numhits: 5, slug: "rameldria", realname: nil, cost: 12, max_lvl: 80},
  {name: "Memetes", description: nil, no: 150, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 150, numhits: 3, slug: "memetes", realname: nil, cost: 5, max_lvl: 40},
  {name: "Hell King Hades", description: nil, no: 151, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 151, numhits: 4, slug: "hell-king-hades", realname: nil, cost: 8, max_lvl: 60},
  {name: "Death God Lodaga", description: nil, no: 152, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 152, numhits: 4, slug: "death-god-lodaga", realname: nil, cost: 12, max_lvl: 80},
  {name: "Lava", description: nil, no: 153, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 153, numhits: 3, slug: "lava", realname: nil, cost: 5, max_lvl: 40},
  {name: "Fire Knight Lava", description: nil, no: 154, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 154, numhits: 4, slug: "fire-knight-lava", realname: nil, cost: 8, max_lvl: 60},
  {name: "Fire God Lava", description: nil, no: 155, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 155, numhits: 7, slug: "fire-god-lava", realname: nil, cost: 12, max_lvl: 80},
  {name: "Captain Mega", description: nil, no: 156, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 156, numhits: 3, slug: "captain-mega", realname: nil, cost: 5, max_lvl: 40},
  {name: "War Captain Mega", description: nil, no: 157, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 157, numhits: 4, slug: "war-captain-mega", realname: nil, cost: 8, max_lvl: 60},
  {name: "Commander Mega", description: nil, no: 158, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 158, numhits: 6, slug: "commander-mega", realname: nil, cost: 12, max_lvl: 80},
  {name: "Gunner Douglas", description: nil, no: 159, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 159, numhits: 8, slug: "gunner-douglas", realname: nil, cost: 5, max_lvl: 40},
  {name: "Gun King Douglas", description: nil, no: 160, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 160, numhits: 10, slug: "gun-king-douglas", realname: nil, cost: 8, max_lvl: 60},
  {name: "Gun God Douglas", description: nil, no: 161, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 161, numhits: 12, slug: "gun-god-douglas", realname: nil, cost: 12, max_lvl: 80},
  {name: "Emilia", description: nil, no: 162, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 162, numhits: 4, slug: "emilia", realname: nil, cost: 5, max_lvl: 40},
  {name: "Princess Emilia", description: nil, no: 163, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 163, numhits: 4, slug: "princess-emilia", realname: nil, cost: 8, max_lvl: 60},
  {name: "Knight Will", description: nil, no: 165, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 165, numhits: 1, slug: "knight-will", realname: nil, cost: 5, max_lvl: 40},
  {name: "Holy Knight Will", description: nil, no: 166, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 166, numhits: 3, slug: "holy-knight-will", realname: nil, cost: 8, max_lvl: 60},
  {name: "God Knight Will", description: nil, no: 167, element_id: 3, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 167, numhits: 5, slug: "god-knight-will", realname: nil, cost: 12, max_lvl: 80},
  {name: "Alice", description: nil, no: 168, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 168, numhits: 3, slug: "alice", realname: nil, cost: 5, max_lvl: 40},
  {name: "Scythe God Alice", description: nil, no: 170, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 170, numhits: 5, slug: "scythe-god-alice", realname: nil, cost: 12, max_lvl: 80},
  {name: "Fire Nyph", description: nil, no: 171, element_id: 1, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-nyph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Water Nyph", description: nil, no: 172, element_id: 2, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-nyph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Earth Nymph", description: nil, no: 173, element_id: 6, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-nymph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Thunder Nymph", description: nil, no: 174, element_id: 5, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-nymph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Light Nymph", description: nil, no: 175, element_id: 3, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-nymph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Dark Nyph", description: nil, no: 176, element_id: 4, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "dark-nyph", realname: nil, cost: 2, max_lvl: 1},
  {name: "Fire Spirit", description: nil, no: 177, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Water Spirit", description: nil, no: 178, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Earth Spirit", description: nil, no: 179, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Thunder Spirit", description: nil, no: 180, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Dark Spirit", description: nil, no: 182, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "dark-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Fire Idol", description: nil, no: 183, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Earth Idol", description: nil, no: 185, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Thunder Idol", description: nil, no: 186, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Light Idol", description: nil, no: 187, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Dark Idol", description: nil, no: 188, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "dark-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Fire Totem", description: nil, no: 189, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Water Totem", description: nil, no: 190, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Earth Totem", description: nil, no: 191, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Thunder Totem", description: nil, no: 192, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Light Totem", description: nil, no: 193, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Dark Totem", description: nil, no: 194, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "dark-totem", realname: nil, cost: 10, max_lvl: 1},
  {name: "Jewel Ghost", description: nil, no: 195, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "jewel-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Jewel King", description: nil, no: 196, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "jewel-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Jewel God", description: nil, no: 197, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "jewel-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Metal Ghost", description: nil, no: 198, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "metal-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Metal King", description: nil, no: 199, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "metal-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Metal God", description: nil, no: 200, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "metal-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Mimc", description: nil, no: 201, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "mimc", realname: nil, cost: 2, max_lvl: 1},
  {name: "Blacksmith Galant", description: nil, no: 203, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 172, numhits: 1, slug: "blacksmith-galant", realname: nil, cost: 4, max_lvl: 30},
  {name: "Bruiser Galant", description: nil, no: 204, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 173, numhits: 1, slug: "bruiser-galant", realname: nil, cost: 6, max_lvl: 40},
  {name: "God Arm Galant", description: nil, no: 205, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 174, numhits: 1, slug: "god-arm-galant", realname: nil, cost: 10, max_lvl: 60},
  {name: "Stya", description: nil, no: 206, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 175, numhits: 5, slug: "stya", realname: nil, cost: 4, max_lvl: 30},
  {name: "Snow Blade Stya", description: nil, no: 207, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 176, numhits: 7, slug: "snow-blade-stya", realname: nil, cost: 6, max_lvl: 40},
  {name: "Frost Queen Stya", description: nil, no: 208, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 177, numhits: 10, slug: "frost-queen-stya", realname: nil, cost: 10, max_lvl: 60},
  {name: "Boxer Nemia", description: nil, no: 209, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 178, numhits: 3, slug: "boxer-nemia", realname: nil, cost: 4, max_lvl: 30},
  {name: "Brawler Nemia", description: nil, no: 210, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 179, numhits: 4, slug: "brawler-nemia", realname: nil, cost: 6, max_lvl: 40},
  {name: "Gaia Fist Nemia", description: nil, no: 211, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 180, numhits: 5, slug: "gaia-fist-nemia", realname: nil, cost: 10, max_lvl: 60},
  {name: "Zeln", description: nil, no: 212, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 181, numhits: nil, slug: "zeln", realname: nil, cost: 4, max_lvl: 30},
  {name: "Spark Kick Zeln", description: nil, no: 213, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 182, numhits: nil, slug: "spark-kick-zeln", realname: nil, cost: 6, max_lvl: 40},
  {name: "Traveler Alma", description: nil, no: 215, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 183, numhits: 3, slug: "traveler-alma", realname: nil, cost: 4, max_lvl: 30},
  {name: "Adventurer Alma", description: nil, no: 216, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 184, numhits: 4, slug: "adventurer-alma", realname: nil, cost: 6, max_lvl: 40},
  {name: "Hero  Alma", description: nil, no: 217, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 185, numhits: 5, slug: "hero-alma", realname: nil, cost: 10, max_lvl: 60},
  {name: "Ninja Oboro", description: nil, no: 218, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 186, numhits: 3, slug: "ninja-oboro", realname: nil, cost: 4, max_lvl: 30},
  {name: "Assasin Oboro", description: nil, no: 219, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 187, numhits: 4, slug: "assasin-oboro", realname: nil, cost: 6, max_lvl: 40},
  {name: "Shadow Oboro", description: nil, no: 220, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 188, numhits: 5, slug: "shadow-oboro", realname: nil, cost: 10, max_lvl: 60},
  {name: "Lancia", description: nil, no: 221, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 189, numhits: nil, slug: "lancia", realname: nil, cost: 5, max_lvl: 40},
  {name: "Hot Chef Lancia", description: nil, no: 222, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 190, numhits: nil, slug: "hot-chef-lancia", realname: nil, cost: 8, max_lvl: 60},
  {name: "Head Chef Lancia", description: nil, no: 223, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 191, numhits: nil, slug: "head-chef-lancia", realname: nil, cost: 12, max_lvl: 80},
  {name: "Elimo", description: nil, no: 224, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 192, numhits: nil, slug: "elimo", realname: nil, cost: 5, max_lvl: 40},
  {name: "Royal Elimo", description: nil, no: 225, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 193, numhits: nil, slug: "royal-elimo", realname: nil, cost: 8, max_lvl: 60},
  {name: "Genius Elimo", description: nil, no: 226, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 194, numhits: nil, slug: "genius-elimo", realname: nil, cost: 12, max_lvl: 80},
  {name: "Pixy Leore", description: nil, no: 227, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 195, numhits: nil, slug: "pixy-leore", realname: nil, cost: 5, max_lvl: 40},
  {name: "Pixy Royal Leore", description: nil, no: 228, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 196, numhits: nil, slug: "pixy-royal-leore", realname: nil, cost: 8, max_lvl: 60},
  {name: "Pixy King Leore", description: nil, no: 229, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 197, numhits: nil, slug: "pixy-king-leore", realname: nil, cost: 12, max_lvl: 80},
  {name: "Tinkerer Elulu", description: nil, no: 230, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 198, numhits: nil, slug: "tinkerer-elulu", realname: nil, cost: 5, max_lvl: 40},
  {name: "Bolt Mallet Elulu", description: nil, no: 232, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 200, numhits: nil, slug: "bolt-mallet-elulu", realname: nil, cost: 12, max_lvl: 80},
  {name: "Knight Aem", description: nil, no: 233, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 201, numhits: nil, slug: "knight-aem", realname: nil, cost: 5, max_lvl: 40},
  {name: "Champion Aem", description: nil, no: 234, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 202, numhits: nil, slug: "champion-aem", realname: nil, cost: 8, max_lvl: 60},
  {name: "Holy Master Aem", description: nil, no: 235, element_id: 3, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 203, numhits: nil, slug: "holy-master-aem", realname: nil, cost: 12, max_lvl: 80},
  {name: "Lemia", description: nil, no: 236, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 204, numhits: nil, slug: "lemia", realname: nil, cost: 5, max_lvl: 40},
  {name: "Necromancer Lemia", description: nil, no: 237, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 205, numhits: nil, slug: "necromancer-lemia", realname: nil, cost: 8, max_lvl: 60},
  {name: "Soul Keeper Lemia", description: nil, no: 238, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 206, numhits: nil, slug: "soul-keeper-lemia", realname: nil, cost: 12, max_lvl: 80},
  {name: "Lorand", description: nil, no: 239, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 207, numhits: nil, slug: "lorand", realname: nil, cost: 5, max_lvl: 40},
  {name: "Professor Lorand", description: nil, no: 240, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 208, numhits: nil, slug: "professor-lorand", realname: nil, cost: 8, max_lvl: 60},
  {name: "Master Lorand", description: nil, no: 241, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 209, numhits: nil, slug: "master-lorand", realname: nil, cost: 12, max_lvl: 80},
  {name: "Dean", description: nil, no: 242, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 210, numhits: nil, slug: "dean", realname: nil, cost: 5, max_lvl: 40},
  {name: "Ice Mage Dean", description: nil, no: 243, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 211, numhits: nil, slug: "ice-mage-dean", realname: nil, cost: 8, max_lvl: 60},
  {name: "Edea", description: nil, no: 245, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 212, numhits: nil, slug: "edea", realname: nil, cost: 5, max_lvl: 40},
  {name: "Earth Knight Edea", description: nil, no: 246, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 213, numhits: nil, slug: "earth-knight-edea", realname: nil, cost: 8, max_lvl: 60},
  {name: "Mother Earth Edea", description: nil, no: 247, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 214, numhits: nil, slug: "mother-earth-edea", realname: nil, cost: 12, max_lvl: 80},
  {name: "Loch", description: nil, no: 248, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 215, numhits: nil, slug: "loch", realname: nil, cost: 5, max_lvl: 40},
  {name: "Shock Bow Loch", description: nil, no: 249, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 216, numhits: nil, slug: "shock-bow-loch", realname: nil, cost: 8, max_lvl: 60},
  {name: "Zeus Bow Loch", description: nil, no: 250, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 217, numhits: nil, slug: "zeus-bow-loch", realname: nil, cost: 12, max_lvl: 80},
  {name: "Fire Ghost", description: nil, no: 254, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Fire King", description: nil, no: 255, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Fire God", description: nil, no: 256, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "fire-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Water Ghost", description: nil, no: 257, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Water King", description: nil, no: 258, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Water God", description: nil, no: 259, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Earth Ghost", description: nil, no: 260, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: nil, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: "Commander Weiss", description: nil, no: 36, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 36, numhits: 6, slug: "commander-weiss", realname: nil, cost: 9, max_lvl: 60},
  {name: "King Squirty", description: nil, no: 46, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 46, numhits: nil, slug: "king-squirty", realname: nil, cost: 3, max_lvl: 30},
  {name: "Geomancer Claris", description: nil, no: 59, element_id: 6, rarity_id: 1, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 59, numhits: 3, slug: "geomancer-claris", realname: nil, cost: 2, max_lvl: 15},
  {name: "Thief Leon", description: nil, no: 79, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 79, numhits: 4, slug: "thief-leon", realname: nil, cost: 3, max_lvl: 30},
  {name: "Zahhak", description: nil, no: 98, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 98, numhits: 5, slug: "zahhak", realname: nil, cost: 6, max_lvl: 40},
  {name: "Firedrake", description: nil, no: 111, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 111, numhits: 3, slug: "firedrake", realname: nil, cost: 5, max_lvl: 40},
  {name: "Water Ruler Sergio", description: nil, no: 126, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 126, numhits: 5, slug: "water-ruler-sergio", realname: nil, cost: 8, max_lvl: 60},
  {name: "World Tree Altro", description: nil, no: 142, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 142, numhits: 4, slug: "world-tree-altro", realname: nil, cost: 8, max_lvl: 60},
  {name: "Goddess Emilia", description: nil, no: 164, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 164, numhits: 6, slug: "goddess-emilia", realname: nil, cost: 12, max_lvl: 80},
  {name: "Scythe Alice", description: nil, no: 169, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 169, numhits: 3, slug: "scythe-alice", realname: nil, cost: 8, max_lvl: 60},
  {name: "Light Spirit", description: nil, no: 181, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-spirit", realname: nil, cost: 5, max_lvl: 1},
  {name: "Water Idol", description: nil, no: 184, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "water-idol", realname: nil, cost: 8, max_lvl: 1},
  {name: "Bat Mimic", description: nil, no: 202, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "bat-mimic", realname: nil, cost: 6, max_lvl: 1},
  {name: "Thunder Kick Zeln", description: nil, no: 214, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-kick-zeln", realname: nil, cost: 10, max_lvl: 60},
  {name: "Inventor Elulu", description: nil, no: 231, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 199, numhits: nil, slug: "inventor-elulu", realname: nil, cost: 8, max_lvl: 60},
  {name: "Earth God", description: nil, no: 262, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Thunder Ghost", description: nil, no: 263, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Thunder King", description: nil, no: 264, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Thunder God", description: nil, no: 265, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "thunder-god", realname: nil, cost: 9, max_lvl: 1},
  {name: "Light Ghost", description: nil, no: 266, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-ghost", realname: nil, cost: 3, max_lvl: 1},
  {name: "Light King", description: nil, no: 267, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-king", realname: nil, cost: 6, max_lvl: 1},
  {name: "Light God", description: nil, no: 268, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "light-god", realname: nil, cost: 9, max_lvl: 1},
  {name: nil, description: nil, no: 269, element_id: 1, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 270, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 271, element_id: 2, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 272, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 273, element_id: 6, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 274, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 275, element_id: 5, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 277, element_id: 3, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 278, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 279, element_id: 4, rarity_id: 2, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 3, max_lvl: 30},
  {name: nil, description: nil, no: 280, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 281, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 6, max_lvl: 40},
  {name: nil, description: nil, no: 282, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 6, max_lvl: 40},
  {name: "Royal Dancer May", description: nil, no: 284, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 218, numhits: nil, slug: "royal-dancer-may", realname: nil, cost: 6, max_lvl: 40},
  {name: nil, description: nil, no: 285, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 6, max_lvl: 40},
  {name: nil, description: nil, no: 286, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 6, max_lvl: 40},
  {name: "Drake Chief Aisha", description: nil, no: 287, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 219, numhits: nil, slug: "drake-chief-aisha", realname: nil, cost: 7, max_lvl: 40},
  {name: "Drake Queen Aisha", description: nil, no: 289, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 221, numhits: nil, slug: "drake-queen-aisha", realname: nil, cost: 15, max_lvl: 80},
  {name: "Twin Gem Rickel", description: nil, no: 290, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 222, numhits: nil, slug: "twin-gem-rickel", realname: nil, cost: 7, max_lvl: 40},
  {name: "Twin Flash Rickel", description: nil, no: 291, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 223, numhits: nil, slug: "twin-flash-rickel", realname: nil, cost: 10, max_lvl: 60},
  {name: "Twin Shot Rickel", description: nil, no: 292, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 224, numhits: nil, slug: "twin-shot-rickel", realname: nil, cost: 15, max_lvl: 80},
  {name: "Twins Il & Mina", description: nil, no: 293, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 225, numhits: nil, slug: "twins-il-mina", realname: nil, cost: 7, max_lvl: 40},
  {name: "Earthly Il & Mina", description: nil, no: 294, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 226, numhits: nil, slug: "earthly-il-mina", realname: nil, cost: 10, max_lvl: 60},
  {name: "Gemini Il & Mina", description: nil, no: 295, element_id: 6, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 227, numhits: nil, slug: "gemini-il-mina", realname: nil, cost: 15, max_lvl: 80},
  {name: "Bolt Pike Amy", description: nil, no: 296, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 228, numhits: nil, slug: "bolt-pike-amy", realname: nil, cost: 7, max_lvl: 40},
  {name: "Bolt Knight Amy", description: nil, no: 297, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 229, numhits: nil, slug: "bolt-knight-amy", realname: nil, cost: 10, max_lvl: 60},
  {name: "Bolt Goddess Amy", description: nil, no: 298, element_id: 5, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 230, numhits: nil, slug: "bolt-goddess-amy", realname: nil, cost: 15, max_lvl: 80},
  {name: "Eight Blade Sefia", description: nil, no: 299, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 231, numhits: nil, slug: "eight-blade-sefia", realname: nil, cost: 7, max_lvl: 40},
  {name: "Blade Storm Sefia", description: nil, no: 300, element_id: 3, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 232, numhits: nil, slug: "blade-storm-sefia", realname: nil, cost: 10, max_lvl: 60},
  {name: "Blade Queen Sefia", description: nil, no: 301, element_id: 3, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 233, numhits: nil, slug: "blade-queen-sefia", realname: nil, cost: 15, max_lvl: 80},
  {name: "Kikuri", description: nil, no: 302, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 234, numhits: nil, slug: "kikuri", realname: nil, cost: 7, max_lvl: 40},
  {name: "Goth Kikuri", description: nil, no: 303, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 235, numhits: nil, slug: "goth-kikuri", realname: nil, cost: 10, max_lvl: 60},
  {name: "Goth Idol Kikuri", description: nil, no: 304, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 236, numhits: nil, slug: "goth-idol-kikuri", realname: nil, cost: 15, max_lvl: 80},
  {name: "Dragon Mimic", description: nil, no: 305, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "dragon-mimic", realname: nil, cost: 15, max_lvl: 1},
  {name: nil, description: nil, no: 306, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: nil, description: nil, no: 307, element_id: 2, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: nil, description: nil, no: 308, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: nil, description: nil, no: 309, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: nil, description: nil, no: 311, element_id: 4, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: "Great Thief Leon", description: nil, no: 312, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 237, numhits: nil, slug: "great-thief-leon", realname: nil, cost: 9, max_lvl: 60},
  {name: nil, description: nil, no: 313, element_id: 2, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 9, max_lvl: 60},
  {name: nil, description: nil, no: 314, element_id: 6, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 9, max_lvl: 60},
  {name: nil, description: nil, no: 315, element_id: 5, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 9, max_lvl: 60},
  {name: nil, description: nil, no: 317, element_id: 4, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 15, max_lvl: 80},
  {name: nil, description: nil, no: 318, element_id: 1, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 10, max_lvl: 60},
  {name: nil, description: nil, no: 319, element_id: 1, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 15, max_lvl: 80},
  {name: nil, description: nil, no: nil, element_id: nil, rarity_id: nil, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: nil, max_lvl: nil},
  {name: "Ice Wizard Dean", description: nil, no: 244, element_id: 2, rarity_id: 5, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 8, numhits: nil, slug: "ice-wizard-dean", realname: nil, cost: 12, max_lvl: 80},
  {name: "Earth King", description: nil, no: 261, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "earth-king", realname: nil, cost: 6, max_lvl: 1},
  {name: nil, description: nil, no: 276, element_id: 5, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 5, max_lvl: 40},
  {name: nil, description: nil, no: 283, element_id: 6, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 6, max_lvl: 40},
  {name: "Drake Lord Aisha", description: nil, no: 288, element_id: 1, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 220, numhits: nil, slug: "drake-lord-aisha", realname: nil, cost: 10, max_lvl: 60},
  {name: nil, description: nil, no: 310, element_id: 3, rarity_id: 3, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: nil, realname: nil, cost: 1, max_lvl: 1},
  {name: "Disciple Zebra", description: nil, no: 316, element_id: 4, rarity_id: 4, base_hp: nil, base_atk: nil, base_def: nil, base_rec: nil, ls_id: nil, bb_id: 171, numhits: nil, slug: "disciple-zebra", realname: nil, cost: 10, max_lvl: 60}
])
